# Generated by Django 5.2.1 on 2025-05-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'verbose_name': 'Граф', 'verbose_name_plural': 'Графы'},
        ),
    ]
